#!/bin/bash
#
# Copyright (C) 2020 i.Dark_Templar <darktemplar@dark-templar-archives.net>
#
# This file is part of DT CGroup Tools.
#
# DT CGroup Tools is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# DT CGroup Tools is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with DT CGroup Tools.  If not, see <http://www.gnu.org/licenses/>.
#

if [ -z "$1" ] ; then
	echo no cgroup name is provided 1>&2
	exit 1
fi

if [ ! -d "$(dirname $1)" ] ; then
	echo parent cgroup directory is missing 1>&2
	exit 1
fi

if [ "$(grep populated "$1/cgroup.events" 2>/dev/null | cut -d ' ' -f 2)" = "1" ] ; then
	echo $1 is already running 1>&2
	exit 1
fi

# setup cgroup
mkdir "$1"
if [ $? -ne 0 ] ; then
	echo failed to create directory $1 1>&2
	exit 1
fi

# run application in cgroup
dt-run-cgroup-helper "$@"

# wait until cgroup is empty
dt-run-cgroup-notifier "$1/cgroup.events"

# clean cgroup
rmdir "$1"
